{% set name = "example-robot-data" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 818c0109d4660b9525da6c420c14773c0192a1c3d110f931d75775345841897f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - make  # [not win]
  host:
    - {{ pin_compatible('pinocchio', min_pin='x.x') }}
    - python
  run:
    - {{ pin_compatible('pinocchio', min_pin='x.x') }}
    - python
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
  imports:
    - example_robot_data

about:
  home: http://github.com/Gepetto/example-robot-data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Set of robot URDFs for benchmarking and developed examples
  dev_url: https://github.com/Gepetto/example-robot-data

extra:
  recipe-maintainers:
    - jcarpent
